### ISSUE TITLE
fetchStories with uuids not working  on Android Kotlin

### ISSUE THREAD

**Issue by daliborristic883** [mikepenz/storyblok-mp-SDK#65]
## About this issue

- Briefly describe the issue
I can get stories from Postman. but sdk fetchStories with uuids not working  on Android Kotlin
- How can the issue be reproduced / sample code
Build Gradle
implementation("com.mikepenz:storyblok-mp-sdk-android:1.2.0")

private var storyblok = Storyblok(STORYBLOCK_TOKEN)
suspend fun fetchStories(): List<Story> {
        val uuids: Array<String> = arrayOf(
            "f5900d63-4a26-4870-b5f4-177671cc74f6",
            "085acfc6-a270-4c47-a652-5c8f24f84247"
        )
        return storyblok.fetchStories(byUuids = uuids)
    }

**Comment by mikepenz** [comment]
Thank you for your report. I'll have a look into this

**Comment by mikepenz** [comment]
(Redacted the token) Won't have time to move at it today but most likely tomorrow

**Comment by daliborristic883** [comment]
Ok thank you.
