### ISSUE TITLE
How to use filter_query in this library?

### ISSUE THREAD

**Issue by daliborristic883** [mikepenz/storyblok-mp-SDK#70]
## About this issue
This is how to use on web app.
```
const fetchedStories = await Storyblok.get(`cdn/stories/`, {
					starts_with: slug,
					filter_query: {
						title: {
							like: `*${query}*`,
						},
					},
				});
```
but this library doesn't provides to use Map<Key: Any> for `filter_query`.

Please help me to fetch stories with `filter_query` as above js codes.

Thank you.

## Details
- [ ] Used library version: 1.2.1
## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/storyblok-mp-SDK/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/storyblok-mp-SDK/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/storyblok-mp-SDK/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/storyblok-mp-SDK/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/storyblok-mp-SDK/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/storyblok-mp-SDK/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
The library exposes the filter query here: 

https://github.com/mikepenz/storyblok-mp-SDK/blob/develop/storyblok-mp-sdk/src/commonMain/kotlin/com/mikepenz/storyblok/sdk/Storyblok.kt#L181

So you can pass in the filter query as string which is then sent to the API. 

Maybe you can explain a bit more on the need for the API, so we can look into exposing additional helpers to construct the filter qery?

**Comment by daliborristic883** [comment]
Github link what you shared doesn't make sense for me.

How can I pass this filter as string?
```
filter_query: {
						title: {
							like: `*${query}*`,
						},
					}
```

**Comment by mikepenz** [comment]
@daliborristic883 I understand now. thank you. 

Your filterquery is sent as `filter_query[title][like]=*test*` via the query parameters. 

I'll look into adjusting the API to support such query parameters, which is currently not handled as needed.

**Comment by daliborristic883** [comment]
Ok thanks.

**Comment by mikepenz** [comment]
Before I release an update with the change. Can you please have a look at the PR and see if it also matches your needs: 
https://github.com/mikepenz/storyblok-mp-SDK/pull/71 ?

**Comment by daliborristic883** [comment]
@mikepenz 
Sorry I can't make sure how to use `filter_query`.
can you please show me how to use it?

Thank you.

**Comment by mikepenz** [comment]
So with the new API (after it's released) you can pass the different arrays like:

```kotlin
storyblok.fetchStories(filterQuery = mapOf("[title][like]" to "*test*"))
```

Do you have more complicated filter setups which would be worth trying prior?

**Comment by mikepenz** [comment]
Releasing it as 1.3.0-rc01 so you can more easily try it out, and we can iterate on it depending on the needs
